{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-09-23T16:49:45.619532Z",
     "start_time": "2020-09-23T16:49:45.477803Z"
    }
   },
   "outputs": [],
   "source": [
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-09-23T17:03:06.948880Z",
     "start_time": "2020-09-23T17:02:46.472641Z"
    },
    "collapsed": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>0</th>\n",
       "      <th>1</th>\n",
       "      <th>2</th>\n",
       "      <th>3</th>\n",
       "      <th>4</th>\n",
       "      <th>5</th>\n",
       "      <th>6</th>\n",
       "      <th>7</th>\n",
       "      <th>8</th>\n",
       "      <th>9</th>\n",
       "      <th>...</th>\n",
       "      <th>16</th>\n",
       "      <th>17</th>\n",
       "      <th>18</th>\n",
       "      <th>19</th>\n",
       "      <th>20</th>\n",
       "      <th>21</th>\n",
       "      <th>22</th>\n",
       "      <th>23</th>\n",
       "      <th>24</th>\n",
       "      <th>25</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>DOT_NUMBER</td>\n",
       "      <td>LEGAL_NAME</td>\n",
       "      <td>DBA_NAME</td>\n",
       "      <td>CARRIER_OPERATION</td>\n",
       "      <td>HM_FLAG</td>\n",
       "      <td>PC_FLAG</td>\n",
       "      <td>PHY_STREET</td>\n",
       "      <td>PHY_CITY</td>\n",
       "      <td>PHY_STATE</td>\n",
       "      <td>PHY_ZIP</td>\n",
       "      <td>...</td>\n",
       "      <td>TELEPHONE</td>\n",
       "      <td>FAX</td>\n",
       "      <td>EMAIL_ADDRESS</td>\n",
       "      <td>MCS150_DATE</td>\n",
       "      <td>MCS150_MILEAGE</td>\n",
       "      <td>MCS150_MILEAGE_YEAR</td>\n",
       "      <td>ADD_DATE</td>\n",
       "      <td>OIC_STATE</td>\n",
       "      <td>NBR_POWER_UNIT</td>\n",
       "      <td>DRIVER_TOTAL</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1</td>\n",
       "      <td>FEDERAL MOTOR CARRIER SAFETY ADMINISTRATION</td>\n",
       "      <td>FMCSA TECHNOLOGY DIVISION</td>\n",
       "      <td>A</td>\n",
       "      <td>N</td>\n",
       "      <td>N</td>\n",
       "      <td>1200 NEW JERSEY AVENUE SE</td>\n",
       "      <td>WASHINGTON</td>\n",
       "      <td>DC</td>\n",
       "      <td>20590</td>\n",
       "      <td>...</td>\n",
       "      <td>(202) 385-2363</td>\n",
       "      <td>NaN</td>\n",
       "      <td>JEFF.LOFTUS@DOT.GOV</td>\n",
       "      <td>16-DEC-19</td>\n",
       "      <td>3000</td>\n",
       "      <td>2019</td>\n",
       "      <td>01-JUN-74</td>\n",
       "      <td>DC</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>10000</td>\n",
       "      <td>POWELL DISTRIBUTING CO INC</td>\n",
       "      <td>NaN</td>\n",
       "      <td>A</td>\n",
       "      <td>N</td>\n",
       "      <td>N</td>\n",
       "      <td>9125 N BURRAGE</td>\n",
       "      <td>PORTLAND</td>\n",
       "      <td>OR</td>\n",
       "      <td>97217</td>\n",
       "      <td>...</td>\n",
       "      <td>(503) 289-5558</td>\n",
       "      <td>(503) 735-0100</td>\n",
       "      <td>JASON@POWELLOIL.COM</td>\n",
       "      <td>25-JUN-20</td>\n",
       "      <td>10000</td>\n",
       "      <td>2019</td>\n",
       "      <td>01-JUN-74</td>\n",
       "      <td>OR</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1000000</td>\n",
       "      <td>JAMES EARL KILLINGSWORTH JR</td>\n",
       "      <td>JAMES KILLINGSWORTH TRUCKING</td>\n",
       "      <td>A</td>\n",
       "      <td>N</td>\n",
       "      <td>N</td>\n",
       "      <td>15 GASLINE ROAD</td>\n",
       "      <td>PHENIX CITY</td>\n",
       "      <td>AL</td>\n",
       "      <td>36870</td>\n",
       "      <td>...</td>\n",
       "      <td>(706) 325-1816</td>\n",
       "      <td>NaN</td>\n",
       "      <td>JIMBOSPLICE2469@YAHOO.COM</td>\n",
       "      <td>18-MAY-20</td>\n",
       "      <td>1</td>\n",
       "      <td>2019</td>\n",
       "      <td>23-JAN-02</td>\n",
       "      <td>AL</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1000002</td>\n",
       "      <td>NEW JERSEY BOOM &amp; ERECTORS INC</td>\n",
       "      <td>NaN</td>\n",
       "      <td>A</td>\n",
       "      <td>N</td>\n",
       "      <td>N</td>\n",
       "      <td>405 INDUSTRIAL PARK DRIVE</td>\n",
       "      <td>MOUNT POCONO</td>\n",
       "      <td>PA</td>\n",
       "      <td>18344</td>\n",
       "      <td>...</td>\n",
       "      <td>(570) 620-1546</td>\n",
       "      <td>(570) 620-1517</td>\n",
       "      <td>GAIL@NJBOOM.COM</td>\n",
       "      <td>03-FEB-20</td>\n",
       "      <td>40000</td>\n",
       "      <td>2019</td>\n",
       "      <td>22-JAN-02</td>\n",
       "      <td>PA</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 26 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "           0                                            1   \\\n",
       "0  DOT_NUMBER                                   LEGAL_NAME   \n",
       "1           1  FEDERAL MOTOR CARRIER SAFETY ADMINISTRATION   \n",
       "2       10000                   POWELL DISTRIBUTING CO INC   \n",
       "3     1000000                  JAMES EARL KILLINGSWORTH JR   \n",
       "4     1000002               NEW JERSEY BOOM & ERECTORS INC   \n",
       "\n",
       "                             2                  3        4        5   \\\n",
       "0                      DBA_NAME  CARRIER_OPERATION  HM_FLAG  PC_FLAG   \n",
       "1     FMCSA TECHNOLOGY DIVISION                  A        N        N   \n",
       "2                           NaN                  A        N        N   \n",
       "3  JAMES KILLINGSWORTH TRUCKING                  A        N        N   \n",
       "4                           NaN                  A        N        N   \n",
       "\n",
       "                          6             7          8        9   ...  \\\n",
       "0                 PHY_STREET      PHY_CITY  PHY_STATE  PHY_ZIP  ...   \n",
       "1  1200 NEW JERSEY AVENUE SE    WASHINGTON         DC    20590  ...   \n",
       "2             9125 N BURRAGE      PORTLAND         OR    97217  ...   \n",
       "3            15 GASLINE ROAD   PHENIX CITY         AL    36870  ...   \n",
       "4  405 INDUSTRIAL PARK DRIVE  MOUNT POCONO         PA    18344  ...   \n",
       "\n",
       "               16              17                         18           19  \\\n",
       "0       TELEPHONE             FAX              EMAIL_ADDRESS  MCS150_DATE   \n",
       "1  (202) 385-2363             NaN        JEFF.LOFTUS@DOT.GOV    16-DEC-19   \n",
       "2  (503) 289-5558  (503) 735-0100        JASON@POWELLOIL.COM    25-JUN-20   \n",
       "3  (706) 325-1816             NaN  JIMBOSPLICE2469@YAHOO.COM    18-MAY-20   \n",
       "4  (570) 620-1546  (570) 620-1517            GAIL@NJBOOM.COM    03-FEB-20   \n",
       "\n",
       "               20                   21         22         23              24  \\\n",
       "0  MCS150_MILEAGE  MCS150_MILEAGE_YEAR   ADD_DATE  OIC_STATE  NBR_POWER_UNIT   \n",
       "1            3000                 2019  01-JUN-74         DC               4   \n",
       "2           10000                 2019  01-JUN-74         OR               1   \n",
       "3               1                 2019  23-JAN-02         AL               1   \n",
       "4           40000                 2019  22-JAN-02         PA               2   \n",
       "\n",
       "             25  \n",
       "0  DRIVER_TOTAL  \n",
       "1             4  \n",
       "2             1  \n",
       "3             1  \n",
       "4             1  \n",
       "\n",
       "[5 rows x 26 columns]"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df = pd.read_csv('./assets/data/FMCSA_CENSUS1_2020Aug.txt', \n",
    "                 sep=\"\\s{4}\", \n",
    "                 delimiter=',',\n",
    "                 header=None, \n",
    "                 engine='python')\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-09-23T17:03:06.962590Z",
     "start_time": "2020-09-23T17:03:06.949727Z"
    }
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>DOT_NUMBER</th>\n",
       "      <th>LEGAL_NAME</th>\n",
       "      <th>DBA_NAME</th>\n",
       "      <th>CARRIER_OPERATION</th>\n",
       "      <th>HM_FLAG</th>\n",
       "      <th>PC_FLAG</th>\n",
       "      <th>PHY_STREET</th>\n",
       "      <th>PHY_CITY</th>\n",
       "      <th>PHY_STATE</th>\n",
       "      <th>PHY_ZIP</th>\n",
       "      <th>...</th>\n",
       "      <th>TELEPHONE</th>\n",
       "      <th>FAX</th>\n",
       "      <th>EMAIL_ADDRESS</th>\n",
       "      <th>MCS150_DATE</th>\n",
       "      <th>MCS150_MILEAGE</th>\n",
       "      <th>MCS150_MILEAGE_YEAR</th>\n",
       "      <th>ADD_DATE</th>\n",
       "      <th>OIC_STATE</th>\n",
       "      <th>NBR_POWER_UNIT</th>\n",
       "      <th>DRIVER_TOTAL</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1</td>\n",
       "      <td>FEDERAL MOTOR CARRIER SAFETY ADMINISTRATION</td>\n",
       "      <td>FMCSA TECHNOLOGY DIVISION</td>\n",
       "      <td>A</td>\n",
       "      <td>N</td>\n",
       "      <td>N</td>\n",
       "      <td>1200 NEW JERSEY AVENUE SE</td>\n",
       "      <td>WASHINGTON</td>\n",
       "      <td>DC</td>\n",
       "      <td>20590</td>\n",
       "      <td>...</td>\n",
       "      <td>(202) 385-2363</td>\n",
       "      <td>NaN</td>\n",
       "      <td>JEFF.LOFTUS@DOT.GOV</td>\n",
       "      <td>16-DEC-19</td>\n",
       "      <td>3000</td>\n",
       "      <td>2019</td>\n",
       "      <td>01-JUN-74</td>\n",
       "      <td>DC</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>10000</td>\n",
       "      <td>POWELL DISTRIBUTING CO INC</td>\n",
       "      <td>NaN</td>\n",
       "      <td>A</td>\n",
       "      <td>N</td>\n",
       "      <td>N</td>\n",
       "      <td>9125 N BURRAGE</td>\n",
       "      <td>PORTLAND</td>\n",
       "      <td>OR</td>\n",
       "      <td>97217</td>\n",
       "      <td>...</td>\n",
       "      <td>(503) 289-5558</td>\n",
       "      <td>(503) 735-0100</td>\n",
       "      <td>JASON@POWELLOIL.COM</td>\n",
       "      <td>25-JUN-20</td>\n",
       "      <td>10000</td>\n",
       "      <td>2019</td>\n",
       "      <td>01-JUN-74</td>\n",
       "      <td>OR</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1000000</td>\n",
       "      <td>JAMES EARL KILLINGSWORTH JR</td>\n",
       "      <td>JAMES KILLINGSWORTH TRUCKING</td>\n",
       "      <td>A</td>\n",
       "      <td>N</td>\n",
       "      <td>N</td>\n",
       "      <td>15 GASLINE ROAD</td>\n",
       "      <td>PHENIX CITY</td>\n",
       "      <td>AL</td>\n",
       "      <td>36870</td>\n",
       "      <td>...</td>\n",
       "      <td>(706) 325-1816</td>\n",
       "      <td>NaN</td>\n",
       "      <td>JIMBOSPLICE2469@YAHOO.COM</td>\n",
       "      <td>18-MAY-20</td>\n",
       "      <td>1</td>\n",
       "      <td>2019</td>\n",
       "      <td>23-JAN-02</td>\n",
       "      <td>AL</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1000002</td>\n",
       "      <td>NEW JERSEY BOOM &amp; ERECTORS INC</td>\n",
       "      <td>NaN</td>\n",
       "      <td>A</td>\n",
       "      <td>N</td>\n",
       "      <td>N</td>\n",
       "      <td>405 INDUSTRIAL PARK DRIVE</td>\n",
       "      <td>MOUNT POCONO</td>\n",
       "      <td>PA</td>\n",
       "      <td>18344</td>\n",
       "      <td>...</td>\n",
       "      <td>(570) 620-1546</td>\n",
       "      <td>(570) 620-1517</td>\n",
       "      <td>GAIL@NJBOOM.COM</td>\n",
       "      <td>03-FEB-20</td>\n",
       "      <td>40000</td>\n",
       "      <td>2019</td>\n",
       "      <td>22-JAN-02</td>\n",
       "      <td>PA</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>1000004</td>\n",
       "      <td>RAY TRUCKING LLC</td>\n",
       "      <td>NaN</td>\n",
       "      <td>C</td>\n",
       "      <td>N</td>\n",
       "      <td>N</td>\n",
       "      <td>218 PEACHTREE ST</td>\n",
       "      <td>WARWICK</td>\n",
       "      <td>GA</td>\n",
       "      <td>31796</td>\n",
       "      <td>...</td>\n",
       "      <td>(229) 535-4140</td>\n",
       "      <td>NaN</td>\n",
       "      <td>MONTOYARAY@YMAIL.COM</td>\n",
       "      <td>01-JUN-20</td>\n",
       "      <td>25000</td>\n",
       "      <td>2019</td>\n",
       "      <td>22-JAN-02</td>\n",
       "      <td>GA</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 26 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "0 DOT_NUMBER                                   LEGAL_NAME  \\\n",
       "1          1  FEDERAL MOTOR CARRIER SAFETY ADMINISTRATION   \n",
       "2      10000                   POWELL DISTRIBUTING CO INC   \n",
       "3    1000000                  JAMES EARL KILLINGSWORTH JR   \n",
       "4    1000002               NEW JERSEY BOOM & ERECTORS INC   \n",
       "5    1000004                             RAY TRUCKING LLC   \n",
       "\n",
       "0                      DBA_NAME CARRIER_OPERATION HM_FLAG PC_FLAG  \\\n",
       "1     FMCSA TECHNOLOGY DIVISION                 A       N       N   \n",
       "2                           NaN                 A       N       N   \n",
       "3  JAMES KILLINGSWORTH TRUCKING                 A       N       N   \n",
       "4                           NaN                 A       N       N   \n",
       "5                           NaN                 C       N       N   \n",
       "\n",
       "0                 PHY_STREET      PHY_CITY PHY_STATE PHY_ZIP  ...  \\\n",
       "1  1200 NEW JERSEY AVENUE SE    WASHINGTON        DC   20590  ...   \n",
       "2             9125 N BURRAGE      PORTLAND        OR   97217  ...   \n",
       "3            15 GASLINE ROAD   PHENIX CITY        AL   36870  ...   \n",
       "4  405 INDUSTRIAL PARK DRIVE  MOUNT POCONO        PA   18344  ...   \n",
       "5           218 PEACHTREE ST       WARWICK        GA   31796  ...   \n",
       "\n",
       "0       TELEPHONE             FAX              EMAIL_ADDRESS MCS150_DATE  \\\n",
       "1  (202) 385-2363             NaN        JEFF.LOFTUS@DOT.GOV   16-DEC-19   \n",
       "2  (503) 289-5558  (503) 735-0100        JASON@POWELLOIL.COM   25-JUN-20   \n",
       "3  (706) 325-1816             NaN  JIMBOSPLICE2469@YAHOO.COM   18-MAY-20   \n",
       "4  (570) 620-1546  (570) 620-1517            GAIL@NJBOOM.COM   03-FEB-20   \n",
       "5  (229) 535-4140             NaN       MONTOYARAY@YMAIL.COM   01-JUN-20   \n",
       "\n",
       "0 MCS150_MILEAGE MCS150_MILEAGE_YEAR   ADD_DATE OIC_STATE NBR_POWER_UNIT  \\\n",
       "1           3000                2019  01-JUN-74        DC              4   \n",
       "2          10000                2019  01-JUN-74        OR              1   \n",
       "3              1                2019  23-JAN-02        AL              1   \n",
       "4          40000                2019  22-JAN-02        PA              2   \n",
       "5          25000                2019  22-JAN-02        GA              2   \n",
       "\n",
       "0 DRIVER_TOTAL  \n",
       "1            4  \n",
       "2            1  \n",
       "3            1  \n",
       "4            1  \n",
       "5            1  \n",
       "\n",
       "[5 rows x 26 columns]"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Reset column names (read with col names in row 0)\n",
    "\n",
    "columns = df.iloc[0]\n",
    "df = df[1:]\n",
    "df.columns= columns\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-09-23T17:07:53.853240Z",
     "start_time": "2020-09-23T17:07:35.944932Z"
    }
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>DOT_NUMBER</th>\n",
       "      <th>LEGAL_NAME</th>\n",
       "      <th>DBA_NAME</th>\n",
       "      <th>CARRIER_OPERATION</th>\n",
       "      <th>HM_FLAG</th>\n",
       "      <th>PC_FLAG</th>\n",
       "      <th>PHY_STREET</th>\n",
       "      <th>PHY_CITY</th>\n",
       "      <th>PHY_STATE</th>\n",
       "      <th>PHY_ZIP</th>\n",
       "      <th>...</th>\n",
       "      <th>TELEPHONE</th>\n",
       "      <th>FAX</th>\n",
       "      <th>EMAIL_ADDRESS</th>\n",
       "      <th>MCS150_DATE</th>\n",
       "      <th>MCS150_MILEAGE</th>\n",
       "      <th>MCS150_MILEAGE_YEAR</th>\n",
       "      <th>ADD_DATE</th>\n",
       "      <th>OIC_STATE</th>\n",
       "      <th>NBR_POWER_UNIT</th>\n",
       "      <th>DRIVER_TOTAL</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>count</th>\n",
       "      <td>1717663</td>\n",
       "      <td>1717583</td>\n",
       "      <td>550758</td>\n",
       "      <td>1717663</td>\n",
       "      <td>1717663</td>\n",
       "      <td>1717663</td>\n",
       "      <td>1717661</td>\n",
       "      <td>1717662</td>\n",
       "      <td>1717662</td>\n",
       "      <td>1717582</td>\n",
       "      <td>...</td>\n",
       "      <td>1709472</td>\n",
       "      <td>597861</td>\n",
       "      <td>1106862</td>\n",
       "      <td>1522264</td>\n",
       "      <td>1097695</td>\n",
       "      <td>1025637</td>\n",
       "      <td>1717663</td>\n",
       "      <td>1717663</td>\n",
       "      <td>1632154</td>\n",
       "      <td>1715204</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>unique</th>\n",
       "      <td>1717663</td>\n",
       "      <td>1599772</td>\n",
       "      <td>466961</td>\n",
       "      <td>3</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>1650789</td>\n",
       "      <td>38448</td>\n",
       "      <td>102</td>\n",
       "      <td>326731</td>\n",
       "      <td>...</td>\n",
       "      <td>1625777</td>\n",
       "      <td>547855</td>\n",
       "      <td>1049786</td>\n",
       "      <td>7415</td>\n",
       "      <td>163401</td>\n",
       "      <td>457</td>\n",
       "      <td>11730</td>\n",
       "      <td>53</td>\n",
       "      <td>1362</td>\n",
       "      <td>1212</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>top</th>\n",
       "      <td>2282576</td>\n",
       "      <td>NONE</td>\n",
       "      <td>OWNER</td>\n",
       "      <td>C</td>\n",
       "      <td>N</td>\n",
       "      <td>N</td>\n",
       "      <td>3377 CALIFORNIA AVE</td>\n",
       "      <td>LOS ANGELES</td>\n",
       "      <td>CA</td>\n",
       "      <td>93722</td>\n",
       "      <td>...</td>\n",
       "      <td>(202) 521-1493</td>\n",
       "      <td>(606) 474-2664</td>\n",
       "      <td>CWILLIAMS798743@GMAIL.COM</td>\n",
       "      <td>18-AUG-20</td>\n",
       "      <td>1</td>\n",
       "      <td>2019</td>\n",
       "      <td>12-JUN-15</td>\n",
       "      <td>CA</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>freq</th>\n",
       "      <td>1</td>\n",
       "      <td>237</td>\n",
       "      <td>376</td>\n",
       "      <td>1100116</td>\n",
       "      <td>1708407</td>\n",
       "      <td>1683236</td>\n",
       "      <td>404</td>\n",
       "      <td>16464</td>\n",
       "      <td>266712</td>\n",
       "      <td>1517</td>\n",
       "      <td>...</td>\n",
       "      <td>3772</td>\n",
       "      <td>229</td>\n",
       "      <td>1383</td>\n",
       "      <td>4674</td>\n",
       "      <td>105603</td>\n",
       "      <td>304740</td>\n",
       "      <td>74118</td>\n",
       "      <td>267348</td>\n",
       "      <td>950128</td>\n",
       "      <td>960631</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>4 rows × 26 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "0      DOT_NUMBER LEGAL_NAME DBA_NAME CARRIER_OPERATION  HM_FLAG  PC_FLAG  \\\n",
       "count     1717663    1717583   550758           1717663  1717663  1717663   \n",
       "unique    1717663    1599772   466961                 3        2        2   \n",
       "top       2282576       NONE    OWNER                 C        N        N   \n",
       "freq            1        237      376           1100116  1708407  1683236   \n",
       "\n",
       "0                  PHY_STREET     PHY_CITY PHY_STATE  PHY_ZIP  ...  \\\n",
       "count                 1717661      1717662   1717662  1717582  ...   \n",
       "unique                1650789        38448       102   326731  ...   \n",
       "top     3377 CALIFORNIA AVE    LOS ANGELES        CA    93722  ...   \n",
       "freq                      404        16464    266712     1517  ...   \n",
       "\n",
       "0            TELEPHONE             FAX              EMAIL_ADDRESS MCS150_DATE  \\\n",
       "count          1709472          597861                    1106862     1522264   \n",
       "unique         1625777          547855                    1049786        7415   \n",
       "top     (202) 521-1493  (606) 474-2664  CWILLIAMS798743@GMAIL.COM   18-AUG-20   \n",
       "freq              3772             229                       1383        4674   \n",
       "\n",
       "0      MCS150_MILEAGE MCS150_MILEAGE_YEAR   ADD_DATE OIC_STATE NBR_POWER_UNIT  \\\n",
       "count         1097695             1025637    1717663   1717663        1632154   \n",
       "unique         163401                 457      11730        53           1362   \n",
       "top                 1                2019  12-JUN-15        CA              1   \n",
       "freq           105603              304740      74118    267348         950128   \n",
       "\n",
       "0      DRIVER_TOTAL  \n",
       "count       1715204  \n",
       "unique         1212  \n",
       "top               1  \n",
       "freq         960631  \n",
       "\n",
       "[4 rows x 26 columns]"
      ]
     },
     "execution_count": 24,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Basic info on df\n",
    "\n",
    "df.describe()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-09-23T17:23:06.449750Z",
     "start_time": "2020-09-23T17:23:03.933826Z"
    }
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0\n",
       "DOT_NUMBER                   0\n",
       "LEGAL_NAME                  80\n",
       "DBA_NAME               1166905\n",
       "CARRIER_OPERATION            0\n",
       "HM_FLAG                      0\n",
       "PC_FLAG                      0\n",
       "PHY_STREET                   2\n",
       "PHY_CITY                     1\n",
       "PHY_STATE                    1\n",
       "PHY_ZIP                     81\n",
       "PHY_COUNTRY                  0\n",
       "MAILING_STREET              37\n",
       "MAILING_CITY                37\n",
       "MAILING_STATE               37\n",
       "MAILING_ZIP                 50\n",
       "MAILING_COUNTRY             36\n",
       "TELEPHONE                 8191\n",
       "FAX                    1119802\n",
       "EMAIL_ADDRESS           610801\n",
       "MCS150_DATE             195399\n",
       "MCS150_MILEAGE          619968\n",
       "MCS150_MILEAGE_YEAR     692026\n",
       "ADD_DATE                     0\n",
       "OIC_STATE                    0\n",
       "NBR_POWER_UNIT           85509\n",
       "DRIVER_TOTAL              2459\n",
       "dtype: int64"
      ]
     },
     "execution_count": 25,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Check for NaN\n",
    "\n",
    "df.isna().sum()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-09-23T17:23:32.762300Z",
     "start_time": "2020-09-23T17:23:31.874636Z"
    }
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "1717663"
      ]
     },
     "execution_count": 28,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df[\"DOT_NUMBER\"].nunique()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-09-23T17:26:26.523793Z",
     "start_time": "2020-09-23T17:26:25.811504Z"
    }
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array(['1', '10000', '1000000', ..., '999993', '999994', '999999'],\n",
       "      dtype=object)"
      ]
     },
     "execution_count": 29,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df[\"DOT_NUMBER\"].unique()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  },
  "toc": {
   "base_numbering": 1,
   "nav_menu": {},
   "number_sections": true,
   "sideBar": true,
   "skip_h1_title": false,
   "title_cell": "Table of Contents",
   "title_sidebar": "Contents",
   "toc_cell": false,
   "toc_position": {},
   "toc_section_display": true,
   "toc_window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
